account/urls.py
from django.urls import path
from account import views

app_name = 'account'

urlpatterns = [
    path('', views.account, name='account'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('kyc-reg/', views.kyc_registration, name='kyc-reg'),
]

digital_payment_prj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from main_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('user/', include('userauths.urls')),
    path('account/', include('account.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_app/urls.py
from django.urls import path
from main_app import views, transfer, transaction, payment_request, credit_card, deposit

app_name = 'main_app'

urlpatterns = [
    path("", views.index, name='index'),
    
    # Transfers
    path("search-acct/", transfer.search_users_acct_number, name='search-acct'),
    path("amount-transfer/<account_number>/", transfer.amount_transfer, name='amount-transfer'),
    path("amount-transfer-process/<account_number>/", transfer.amount_transfer_process, name='amount-transfer-process'),
    path("transfer-confirmation/<account_number>/<transaction_id>/", transfer.transfer_confirmation, name='transfer-confirmation'),
    path("transfer-process/<account_number>/<transaction_id>/", transfer.transfer_process, name='transfer-process'),
    path("transfer-completed/<account_number>/<transaction_id>/", transfer.transfer_completed, name='transfer-completed'),
    
    # Transactions
    path("transactions/", transaction.transaction_list, name="transactions"),
    path("transaction-detail/<transaction_id>/", transaction.transaction_detail, name="transaction-detail"),
    
    # Payment Request
    path("request-search-acct/", payment_request.search_users_request, name="request-search-acct"),
    path("amount-request/<account_number>/", payment_request.amount_request, name="amount-request"),
    path("amount-request-process/<account_number>/", payment_request.amount_request_process, name="amount-request-process"),
    path("amount-request-confirmation/<account_number>/<transaction_id>/", payment_request.amount_request_confirmation, name="amount-request-confirmation"),
    path("amount-request-final-process/<account_number>/<transaction_id>/", payment_request.amount_request_final_process, name="amount-request-final-process"),
    path("amount-request-completed/<account_number>/<transaction_id>/", payment_request.amount_request_completed, name="amount-request-completed"),
    
    # Request Settlement
    path("settlement-confirmation/<account_number>/<transaction_id>/", payment_request.settlement_confirmation, name="settlement-confirmation"),
    path("settlement-processing/<account_number>/<transaction_id>/", payment_request.settlement_processing, name="settlement-processing"),
    path("settlement-completed/<account_number>/<transaction_id>/", payment_request.settlement_completed, name="settlement-completed"),
    path("delete-request/<account_number>/<transaction_id>/", payment_request.delete_payment_request, name="delete-request"),
    
    # Credit Card 
    path("card/<card_id>/", credit_card.card_detail, name="card-detail"),
    path("fund-card/<card_id>/", credit_card.fund_card, name="fund-card"),
    path("withdraw-fund/<card_id>/", credit_card.withdraw_fund, name="withdraw-fund"),
    path("delete-card/<card_id>/", credit_card.delete_card, name="delete-card"),
    
    # Deposit
    path('deposit-money/<account_number>/', deposit.deposit_money, name='deposit-money'),
    path("deposit-money-process/<account_number>/", deposit.deposit_money_process, name='deposit-money-process'),
    path('deposit-money-confirmation/<account_number>/<transaction_id>/', deposit.deposit_money_confirmation, name='deposit-money-confirmation'),
    path("deposit-process/<account_number>/<transaction_id>/", deposit.deposit_process, name='deposit-process'),
    path("deposit-completed/<account_number>/<transaction_id>/", deposit.deposit_completed, name='deposit-completed'),

]

templates/payment_request/amount-request-completed.html
{% extends "partials/dashboard-base.html" %}
{% load static %}
{% load humanize %}
{% block content %}

    <!-- Dashboard Section start -->
    <section class="dashboard-section body-collapse pay step step-2 step-3 receive-3">
        <div class="overlay pt-120">
            <div class="container-fluid">
                <div class="main-content">
                    <div class="head-area d-flex align-items-center justify-content-between">
                        <h4>Request Payment</h4>
                    </div>
                    <div class="request-submitted pb-120 text-center">
                        <div class="top-area">
                            <div class="icon-area">
                                <img src="{% static 'assets1/images/icon/success-icon.png' %}" alt="icon" style="width: 200px; height: 200px;">
                            </div>
                            <h3>Sent!</h3>
                            <p>Payment Request <b>{{transaction.transaction_id}}</b> was sent to <b>{{account.user.kyc.full_name}}</b></p>
                            <h5><a href=""><b>View Detail</b></a> | <a href=""><b>Send Another Payment</b></a></h5>
                        </div>
                        {% comment %} <div class="share-link">
                            <p>Share direct link with your payer</p>
                            <ul class="d-flex align-items-center justify-content-center">
                                <li>
                                    <a href="javascript:void(0)"><img src="{% static 'assets1/images/icon/whatsapp.png' %}" alt="icon"></a>
                                </li>
                                <li>
                                    <a href="javascript:void(0)"><img src="{% static 'assets1/images/icon/skype.png' %}" alt="icon"></a>
                                </li>
                                <li>
                                    <a href="javascript:void(0)"><img src="{% static 'assets1/images/icon/messenger.png' %}" alt="icon"></a>
                                </li>
                                <li>
                                    <a href="javascript:void(0)"><img src="{% static 'assets1/images/icon/copy-link.png' %}" alt="icon"></a>
                                </li>
                            </ul>
                        </div> {% endcomment %}
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Dashboard Section end -->

{% endblock content %}

templates/payment_request/amount-request-confirmation.html
{% extends "partials/dashboard-base.html" %}
{% load static %}
{% load humanize %}
{% block content %}

    <!-- Dashboard Section start -->
    <section class="dashboard-section body-collapse pay step step-2 step-3">
        <div class="overlay pt-120">
            <div class="container-fluid">
                <div class="main-content">
                    <div class="head-area d-flex align-items-center justify-content-between">
                        <h4>Request Payment</h4>
                    </div>
                    <div class="choose-recipient">
                        <div class="step-area">
                            <span class="mdr">Step 3 of 3</span>
                            <h5>Confirm Request</h5>
                        </div>
                        <div class="user-select">
                            <div class="single-user">
                                <div class="left d-flex align-items-center">
                                    <div class="img-area">
                                        <img src="{{ account.user.kyc.image.url }}" style="width: 100px; height: 100px; border-radius: 50%; object-fit: cover"  alt="image">
                                    </div>
                                    <div class="text-area">
                                        <p>{{ account.user.kyc.full_name|title }}</p>
                                        <span class="mdr"><b>{{ account.account_number }}</b></span><br>
                                        <span class="mdr">{{ account.user.email }}</span>
                                    </div>
                                </div>
                                {% comment %} <div class="right">
                                    <a href="{% url "main_app:request-search-acct" %}">
                                        <i class="icon-h-edit"></i>
                                        Edit
                                    </a>
                                </div> {% endcomment %}
                            </div>
                        </div>
                    </div>
                    <div class="payment-details">
                        <div class="top-area">
                            <h5><b>Payment Details</b></h5>
                            <div class="right">
                                <a href="{% url "main_app:amount-request" account.account_number %}">
                                    Edit Payment Details
                                </a>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xl-6">
                                <ul class="details-list">
                                    <li>
                                        <span><b>{{ request.user.kyc.full_name }}</b> --> Requested</span>
                                        <b>${{ transaction.amount|intcomma }} USD</b>
                                    </li>
                                    <li>
                                        <span><b>{{ account.user.kyc.full_name }}</b> --> To Send</span>
                                        <b>${{ transaction.amount|intcomma }} USD</b>
                                    </li>
                                    <li>
                                        <span>Fee</span>
                                        <b>Free</b>
                                    </li>
                                    <li>
                                        <span>Description</span>
                                        <b>{{transaction.description}}</b>
                                    </li>
                                    <li>
                                        <span>Transfer was initiated on </span>
                                        <b>{{transaction.date}} </b>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <form action="#">
                        <div class="checkbox">
                            <input type="checkbox" id="confirm">
                            <label for="confirm">I confirm the payment details above</label>
                        </div>
                        <div class="footer-area mt-40">
                            {% comment %} <a href="{% url "main_app:amount-request" account.account_number %}">Go Back</a> {% endcomment %}
                            <a href="" class="transferMod active" data-bs-toggle="modal" data-bs-target="#transferMod">Submit Request</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- Dashboard Section end -->

    <!-- Transfer Popup start -->
    <div class="transfer-popup">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-6">
                    <div class="modal fade" id="transferMod" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered">
                            <ul class="nav nav-tabs d-none" role="tablist">
                                <li class="nav-item" role="presentation">
                                    <button class="nav-link active" id="transfer-tab" data-bs-toggle="tab" data-bs-target="#transfer" type="button" role="tab" aria-controls="transfer" aria-selected="true">transfer</button>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <button class="nav-link" id="success-tab" data-bs-toggle="tab" data-bs-target="#success" type="button" role="tab" aria-controls="success" aria-selected="false">Confirm</button>
                                </li>
                            </ul>
                            <div class="tab-content">
                                <div class="tab-pane fade show active" id="transfer" role="tabpanel" aria-labelledby="transfer-tab">
                                    <div class="modal-content">
                                        <div class="modal-header mb-60 justify-content-between">
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">X</button>
                                        </div>
                                        <div class="main-content">
                                            <h4>Confirm Your Request</h4>
                                            <p>Please enter your four (4) digit PIN number</p>
                                            <form action="{% url "main_app:amount-request-final-process" account.account_number transaction.transaction_id %}" method="POST">
                                                {% csrf_token %}
                                                <div class="userInput">
                                                    <input minlength="4" maxlength="4" name="pin-number" type="password">
                                                </div>
                                                <button type="submit" class="mt-60 confirm">Confirm</button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                                {% comment %} <div class="tab-pane fade" id="success" role="tabpanel" aria-labelledby="success-tab">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="btn-close d-md-none d-block" data-bs-dismiss="modal" aria-label="Close"><i class="fa-solid fa-xmark"></i></button>
                                        </div>
                                        <div class="main-content text-center pt-120 pb-120">
                                            <img src="{% static 'assets/images/icon/success.png' %}" alt="icon">
                                            <h3>Success</h3>
                                            <p>Transfer was completed.</p>
                                        </div>
                                    </div>
                                </div> {% endcomment %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Transfer Popup start -->

{% endblock content %}

templates/payment_request/amount-request.html
{% extends "partials/dashboard-base.html" %}
{% load static %}
{% load humanize %}
{% block content %}

    <!-- Dashboard Section start -->
    <section class="dashboard-section body-collapse pay step step-2">
        <div class="overlay pt-120">
            <div class="container-fluid">
                <div class="main-content">
                    <div class="head-area d-flex align-items-center justify-content-between">
                        <h4>Request Payment</h4>
                    </div>
                    <div class="choose-recipient">
                        <div class="step-area">
                            <span class="mdr">Step 2 of 3</span>
                            <h5>Set Amount to Request</h5>
                        </div>
                        <div class="user-select">
                            <div class="single-user">
                                <div class="left d-flex align-items-center">
                                    <div class="img-area">
                                        <img src="{{ account.user.kyc.image.url }}" style="width: 100px; height: 100px; border-radius: 50%; object-fit: cover"  alt="image">
                                    </div>
                                    <div class="text-area">
                                        <p>{{ account.user.kyc.full_name|title }}</p>
                                        <span class="mdr"><b>{{ account.account_number }}</b></span><br>
                                        <span class="mdr">{{ account.user.email }}</span>
                                    </div>
                                </div>
                                <div class="right">
                                    <a href="{% url "main_app:request-search-acct" %}">
                                        Edit
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <form action={% url "main_app:amount-request-process" account.account_number %}  method="POST">
                        {% csrf_token %}
                        <div class="send-banance">
                            <span class="mdr">Requested Amount</span>
                            <div class="input-area">
                                <input class="xxlr" id="amount-request" name="amount-request" placeholder="Enter Requested Amount $" type="number">
                                {% comment %} <select>
                                    <option value="1">USD</option>
                                    <option value="2">USD</option>
                                    <option value="3">USD</option>
                                </select> {% endcomment %}
                            </div>
                        </div>

                        <div class="send-banance pt-0 mt-0">
                            <span class="mdr">Request Description</span>
                            <div class="input-area">
                                <input class="xxlr" name="description" placeholder="Request for..." type="text">
                            </div>
                        </div>

                        <div class="footer-area mt-40">
                            <a href="{% url "main_app:request-search-acct" %}">Previous Step</a>
                            <button type="submit" style="padding: 10px 30px; border-radius: 10px; background: rgb(98, 0, 255); color: #fff" class="active">Next</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- Dashboard Section end -->

{% endblock content %}

templates/payment_request/settlement-completed.html
{% extends "partials/dashboard-base.html" %}
{% load static %}
{% load humanize %}
{% block content %}

    <!-- Dashboard Section start -->
    <section class="dashboard-section body-collapse pay step step-2 step-3 receive-3">
        <div class="overlay pt-120">
            <div class="container-fluid">
                <div class="main-content">
                    <div class="head-area d-flex align-items-center justify-content-between">
                        <h4>Payment Request</h4>
                    </div>
                    <div class="request-submitted pb-120 text-center">
                        <div class="top-area">
                            <div class="icon-area">
                                <img src="{% static 'assets1/images/icon/success.png' %}" alt="icon" style="width: 200px; height: 200px;">
                            </div>
                            <h3>Approved!</h3>
                            <p>Payment Request <b>{{transaction.transaction_id}}</b> was sent to <b>{{account.user.kyc.full_name}}</b></p>
                            <h5><a href=""><b>View Detail</b></a> | <a href=""><b>Send Another Payment</b></a></h5>
                        </div>
                        {% comment %} <div class="share-link">
                            <p>Share direct link with your payer</p>
                            <ul class="d-flex align-items-center justify-content-center">
                                <li>
                                    <a href="javascript:void(0)"><img src="{% static 'assets1/images/icon/whatsapp.png' %}" alt="icon"></a>
                                </li>
                                <li>
                                    <a href="javascript:void(0)"><img src="{% static 'assets1/images/icon/skype.png' %}" alt="icon"></a>
                                </li>
                                <li>
                                    <a href="javascript:void(0)"><img src="{% static 'assets1/images/icon/messenger.png' %}" alt="icon"></a>
                                </li>
                                <li>
                                    <a href="javascript:void(0)"><img src="{% static 'assets1/images/icon/copy-link.png' %}" alt="icon"></a>
                                </li>
                            </ul>
                        </div> {% endcomment %}
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Dashboard Section end -->

{% endblock content %}

templates/payment_request/settlement-confirmation.html
{% extends "partials/dashboard-base.html" %}
{% load static %}
{% load humanize %}
{% block content %}

    <!-- Dashboard Section start -->
    <section class="dashboard-section body-collapse pay step step-2 step-3">
        <div class="overlay pt-120">
            <div class="container-fluid">
                <div class="main-content">
                    <div class="head-area d-flex align-items-center justify-content-between">
                        <h4>Make a Payment</h4>
                    </div>
                    <div class="choose-recipient">
                        <div class="step-area">
                            <span class="mdr">Step 3 of 3</span>
                            <h5>Confirm Your Transfer</h5>
                        </div>
                        <div class="user-select">
                            <div class="single-user">
                                <div class="left d-flex align-items-center">
                                    <div class="img-area">
                                        <img src="{{ account.user.kyc.image.url }}" style="width: 100px; height: 100px; border-radius: 50%; object-fit: cover"  alt="image">
                                    </div>
                                    <div class="text-area">
                                        <p>{{ account.user.kyc.full_name|title }}</p>
                                        <span class="mdr"><b>{{ account.account_number }}</b></span><br>
                                        <span class="mdr">{{ account.user.email }}</span>
                                    </div>
                                </div>
                                {% comment %} <div class="right">
                                    <a href="{% url "main_app:search-acct" %}">
                                        <i class="icon-h-edit"></i>
                                        Edit
                                    </a>
                                </div> {% endcomment %}
                            </div>
                        </div>
                    </div>
                    <div class="payment-details">
                        <div class="top-area">
                            <h6>Payment Details</h6>
                            {% comment %} <div class="right">
                                <a href="javascript:void(0)">
                                    <i class="icon-h-edit"></i>
                                    Edit
                                </a>
                            </div> {% endcomment %}
                        </div>
                        <div class="row">
                            <div class="col-xl-6">
                                <ul class="details-list">
                                    <li>
                                        <span><b>{{request.user.kyc.full_name}}</b> --> Sending</span>
                                        <b>${{transaction.amount|intcomma}} USD</b>
                                    </li>
                                    <li>
                                        <span><b>{{account.user.kyc.full_name}}</b> --> Receiving</span>
                                        <b>${{transaction.amount|intcomma}} USD</b>
                                    </li>
                                    <li>
                                        <span>Recipient's Email</span>
                                        <b>{{account.user.email}}</b>
                                    </li>
                                    <li>
                                        <span>Fee</span>
                                        <b>Free</b>
                                    </li>
                                    <li>
                                        <span>Description</span>
                                        <b>{{transaction.description}}</b>
                                    </li>
                                    <li>
                                        <span>Transfer was initiated on </span>
                                        <b>{{transaction.date}} </b>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <form action="#">
                        <div class="checkbox">
                            <input type="checkbox" id="confirm">
                            <label for="confirm">I confirm the payment request details above</label>
                        </div>
                        <div class="footer-area mt-40">
                            <a href="{% url "main_app:transactions" %}">Go Back</a>
                            <a href="javascript:void(0)" class="transferMod active" data-bs-toggle="modal" data-bs-target="#transferMod">Approve</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- Dashboard Section end -->

    <!-- Transfer Popup start -->
    <div class="transfer-popup">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-6">
                    <div class="modal fade" id="transferMod" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered">
                            <ul class="nav nav-tabs d-none" role="tablist">
                                <li class="nav-item" role="presentation">
                                    <button class="nav-link active" id="transfer-tab" data-bs-toggle="tab" data-bs-target="#transfer" type="button" role="tab" aria-controls="transfer" aria-selected="true">transfer</button>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <button class="nav-link" id="success-tab" data-bs-toggle="tab" data-bs-target="#success" type="button" role="tab" aria-controls="success" aria-selected="false">Confirm</button>
                                </li>
                            </ul>
                            <div class="tab-content">
                                <div class="tab-pane fade show active" id="transfer" role="tabpanel" aria-labelledby="transfer-tab">
                                    <div class="modal-content">
                                        <div class="modal-header mb-60 justify-content-between">
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">X</button>
                                        </div>
                                        <div class="main-content">
                                            <h4>Confirm Transfer!</h4>
                                            <p>Please enter your four (4) digit PIN number</p>
                                            <form action="{% url "main_app:settlement-processing" account.account_number transaction.transaction_id %}" method="POST">
                                                {% csrf_token %}
                                                <div class="userInput">
                                                    <input minlength="4" maxlength="4" name="pin-number" type="password">
                                                </div>
                                                <button type="submit" class="mt-60 confirm">Confirm</button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="success" role="tabpanel" aria-labelledby="success-tab">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="btn-close d-md-none d-block" data-bs-dismiss="modal" aria-label="Close"><i class="fa-solid fa-xmark"></i></button>
                                        </div>
                                        <div class="main-content text-center pt-120 pb-120">
                                            <img src="{% static 'assets/images/icon/success.png' %}" alt="icon">
                                            <h3>Success</h3>
                                            <p>Request was approved.</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Transfer Popup start -->

{% endblock content %}